### ISSUE TITLE
Zero Sized Closure assumption is Unsound

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/procspawn#18]
The assumption that zero sized closures are sound is demonstrably incorrect: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a999aaaa716f06443566a9970ae8317a

Mitosis which this is based on originally used `fn()` pointers but that also ran into problems with address space randomization protections. See https://github.com/Manishearth/mitosis/issues/5 and https://github.com/Manishearth/mitosis/commit/5ab38647927a74f4a46c0ca5a5cae99835940437

**Comment by danielhenrymantilla** [comment]
I think that if the initial closure is leaked, then the pattern would be "less unsound":

```rust

fn unsound<F : FnOnce()> (f: F)
{
    if ::core::mem::size_of::<F>() > 0 { return; }
    ::core::mem::forget(f);
    // ...
    let f: F = unsafe { ::core::mem::zeroed() };
    f();
}
```

This is because we would be kind of "moving" / "teleporting" the initial `f` into the new `let f` binding

___

> Mitosis which this is based on originally used fn() pointers but that also ran into problems with address space randomization protections

I'm afraid that using closures as input does not solve the issue, since `fn()` pointers are also capture-less closures (`fn() : Fn()`): https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5d4b75978edd437e2ee6e2789ae45dec

**Comment by mitsuhiko** [comment]
@danielhenrymantilla the leaking of the closure is really interesting. There is a lot of bullshit you can do which completely breaks what we're doing here at the moment though.

I just wondered what would happen if one starts boxing an `FnOnce` and predictably weird stuff happens.

**Comment by mitsuhiko** [comment]
I wonder if it's "good enough" to check for `std::mem::needs_drop` here.
