### ISSUE TITLE
Is there any way to spawn a process asynchronously?

### ISSUE THREAD

**Issue by mkgilbert** [mitsuhiko/procspawn#42]
First, thank you for developing this crate! 

I saw that experimental async support was removed in version 0.9.0 and I'm hoping to get input on how to achieve spawning a process using async/await. My use case is that I need to spawn a separate process as a different user, but I have to do it from within a Rocket app, which is multi-threaded. My limited understanding (I'm new to Rust and async concepts as well) is that spawning a process from within an async runtime like tokio should also be handled with async/await, but I'm not sure how crucial that is.  

Any thoughts on whether or not I should use `procspawn` for this or if there is another way to achieve what I need to do?

Thanks!

**Comment by mitsuhiko** [comment]
There is not a ton of point in spawning a process async since there are no real system APIs for this. In theory more threads could be created but I'm not sure if there is much of a point in doing that considering there is already a worker pool available. `procspawn` should work well enough for this.

**Comment by mkgilbert** [comment]
Thank you so much for the reply and explanation! That makes sense.
